# Copyright 2026 GrillKit Contributors
# SPDX-License-Identifier: Apache-2.0
"""Tests for audio probe WAV helpers."""

from io import BytesIO
import wave

from app.ai.audio_probe import minimal_wav_bytes
from app.shared.infrastructure.audio_wav import validate_wav_bytes


class TestAudioProbe:
    """Tests for minimal WAV generation."""

    def test_minimal_wav_bytes_is_valid_wav(self):
        """Generated bytes parse as mono PCM WAV."""
        payload = minimal_wav_bytes()
        with wave.open(BytesIO(payload), "rb") as wav_file:
            assert wav_file.getnchannels() == 1
            assert wav_file.getsampwidth() == 2
            assert wav_file.getframerate() == 16000

    def test_minimal_wav_bytes_passes_canonical_validation(self):
        """Generated probe WAV satisfies shared audio answer rules."""
        validate_wav_bytes(minimal_wav_bytes())
